### ISSUE TITLE
Refactor `firehose-near` to use `firehose-core`

### ISSUE THREAD

**Issue by maoueh** [streamingfast/sf-near#3]
Next step in the refactoring of Firehose for integrators is to bring `firehose-core` into `firehose-near` and add the missing building blocks in `firehose-core` that would be missing. 

There is sadly not an exhaustive list for that, but we have:
- Index builder (app and necessary hooks to provider chain specific indexer code)
- Some extensions points for "extra" tools (or bring missing tools in `firehose-core`)
- Ensure current `node-manager` in `firehose-near` still works.

**Comment by matthewdarwin** [comment]
This has been done.
